[package]
name = "nostr-relay-pool-sansio"
version = "0.42.0"
edition = "2021"
description = "I/O-free (Sans-I/O) nostr relay pool implementation."
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
rust-version.workspace = true
keywords = ["nostr", "relay", "pool", "sans-io"]

[dependencies]
